### ISSUE TITLE
BUG: Clean build fails with `rm: cannot remove '/etc/calamares/modules/before_bootloader_context.conf': No such file or directory`

### ISSUE THREAD

**Issue by Validark** [rhino-linux/os#95]
**Platform:**
amd64 (I am running Ubuntu-based PopOS)

**Describe the bug**
Running the commands in the readme results in the following:

```
rm: cannot remove '/etc/calamares/modules/before_bootloader_context.conf': No such file or directory
touch: cannot touch '/etc/calamares/modules/before_bootloader_context.conf': No such file or directory
/root/002-install-pacstall.chroot: 26: cannot create /etc/calamares/modules/before_bootloader_context.conf: Directory nonexistent
/root/002-install-pacstall.chroot: 54: cannot create /etc/calamares/modules/umount.conf: Directory nonexistent
E: config/hooks/live/002-install-pacstall.chroot failed (exit non-zero). You should check for errors.
E: An unexpected failure occurred, exiting...
P: Begin unmounting filesystems...
P: Saving caches...
```

**To Reproduce**
```
git clone https://github.com/rhino-linux/os.git
cd os
sudo apt-get update && sudo apt-get install --reinstall debootstrap -y
sudo mv /usr/share/debootstrap/functions functions
sudo patch -i 0002-remove-WRONGSUITE-error.patch
sudo mv functions /usr/share/debootstrap/functions
sudo ln -sfn /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/lunar
sudo dpkg -i debs/live-build_*_all.deb
sudo cp binary_grub-efi /usr/lib/live/build/binary_grub-efi
sudo chmod -R +x build.sh etc/auto/config etc/terraform.conf etc/
sudo ./build.sh etc/terraform.conf
```

**Expected behavior**
No build error

**Comment by cat-master21** [comment]
I managed to figure out the issue, it looks like the APT package that provides the files (`calamares-settings-ubuntu-common`) now depends on `snapd-seed-glue` (which depends on Snap), added in latest Ubuntu version. I will fix this soon by removing the dependant Calamares module that needs it, as we use our own theme and other stuff anyway.

**Comment by cat-master21** [comment]
@Validark Thanks for waiting, try building with the latest commit now ([`de67306`](https://github.com/rhino-linux/os/commit/de673065164b17ff72b48b9bf7478b6decaa3c4d)). This should solve your problem so this issue is closed now, but feel free to reopen it if not.

**Comment by oklopfer** [comment]
@cat-master21 
```
[~] rhino-live@rhino-live $ sudo -E calamares -D6
qt.qpa.theme.dbus: Session DBus not running.
qt.qpa.theme.dbus: Application will not react to setting changes.
 Check your DBus installation.
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: Windows, Fusion
06:27:07 [6]: Calamares::Settings::Settings(const QString&, bool)
    Using Calamares settings file at "/etc/calamares/settings.conf" 
06:27:07 [2]: void Calamares::YAML::explainException(const YAML::Exception&, const QByteArray&, const QString&)
    WARNING: YAML error  yaml-cpp: error at line 70, column 7: illegal map value in "/etc/calamares/settings.conf" . 
06:27:07 [2]: void Calamares::YAML::explainException(const YAML::Exception&, const QByteArray&)
    WARNING: offending YAML data: - show: 
06:27:07 [1]: static Calamares::Settings* Calamares::Settings::init(bool)
    ERROR: FATAL: no sequence set. 
```
From: https://github.com/rhino-linux/os/actions/runs/12555748344

**Comment by oklopfer** [comment]
Here is the file BTW:
```
---
modules-search: [ local ]

instances:
- id: before_bootloader_mkdirs
  module: contextualprocess
  config: before_bootloader_mkdirs_context.conf
- id: before_bootloader
  module: contextualprocess
  config: before_bootloader_context.conf
- id: logs
  module: shellprocess
  config: shellprocess_logs.conf
- id: bug-LP#1829805
  module: shellprocess
  config: shellprocess_bug-LP#1829805.conf
- id: add386arch
  module: shellprocess
  config: shellprocess_add386arch.conf
- id: oemprep
  module: shellprocess
  config: shellprocess_oemprep.conf
- id: fixconkeys_part1
  module: shellprocess
  config: shellprocess_fixconkeys_part1.conf
- id: fixconkeys_part2
  module: shellprocess
  config: shellprocess_fixconkeys_part2.conf
- id: fix-oem-uid
  module: shellprocess
  config: shellprocess_fix_oem_uid.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - automirror
  process
  - dracutlukscfg
  - dracut
  - contextualprocess@before_bootloader_mkdirs
  - shellprocess@bug-LP#1829805
  - shellprocess@fixconkeys_part1
  - shellprocess@fixconkeys_part2
  - shellprocess@add386arch
  - contextualprocess@before_bootloader
  - grubcfg
  - bootloader
  - shellprocess@logs
  - umount
- show:
  - finished

branding: rhino
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
```
